name: Deploy to Staging
on:
  push:
    branches:
      - 'master'
jobs:

  run:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup ENV files
      run: cp .env.stage .env;

    - name: Run build and test
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: Extract variables
      shell: bash
      run: |
        echo "::set-output name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        echo "::set-output name=GIT_SHA::$(git rev-parse HEAD)"
        echo "::set-output name=GIT_SHA_SHORT::$(git rev-parse --short HEAD)"
      id: extract_variables

    - name: Deploy
      uses: reggionick/s3-deploy@v2
      with:
        folder: build
        bucket: ${{ secrets.STAGE_S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true

    - name: Slack notification
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        channel-id: 'C082HTBD1'
        slack-message: 'A new version of PID Services has been deployed to stage.'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}