name: Release to Production
on:
  release:
    types: [published]
jobs:

  run:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup ENV files
      run: cp .env.production .env;

    - name: Run build and test
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: Deploy
      uses: reggionick/s3-deploy@v2
      with:
        folder: build
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true